server.port=8080
jwt.secret=oiboanoiteseraquevaitergoldorayanhojeendrickdeviaterentradogersonmedadez
gateway.public.url=http://localhost:8080
automanager.core.url=http://localhost:8081
api.clientes.url=http://localhost:8082
api.funcionarios.url=http://localhost:8083
api.catalogo.url=http://localhost:8084
api.vendas.url=http://localhost:8085
api.veiculos.url=http://localhost:8086
